# Supabase Project Configuration

[project]
# A unique project ID for this Supabase project
id = "gardenscape-pro"

[api]
# Port for the local Supabase API
port = 54321
# Schemas to expose in the API
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path
extra_search_path = ["public", "extensions"]
# Maximum number of rows in a single response
max_rows = 1000

[db]
# Port for the local database
port = 54322
# The database major version
major_version = 15
# Database pooler configuration
pooler_default_pool_size = 20
pooler_max_client_conn = 100

[db.pooler]
enabled = true
# Connection pool mode: "transaction" | "session" | "statement"
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
# Port for Supabase Studio
port = 54323
# Studio update notifications
api_url = "http://localhost:54321"

[inbucket]
# Port for the email testing server
port = 54324

[storage]
# The maximum file size allowed for uploads (50MB)
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = true

[auth]
# The URL of your app
site_url = "http://localhost:5000"
# A list of allowed redirect URLs
additional_redirect_urls = ["https://localhost:5000"]
# How long tokens are valid for (in seconds). Defaults to 3600 (1 hour)
jwt_expiry = 3600
# Enable email confirmations
enable_signup = true
# Enable email link sign in
enable_confirmations = false
# Allow new user signups
enable_anonymous_sign_ins = false

[auth.email]
# Enable email auth
enable_signup = true
# Require email confirmation
enable_confirmations = false
# Template for confirmation emails
template.confirmation = """
<h2>Confirm your email</h2>
<p>Follow this link to confirm your email:</p>
<p><a href="{{ .ConfirmationURL }}">Confirm your email address</a></p>
"""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""

# Email testing configuration (local development)
[local]
# Use InBucket for local email testing
inbucket_enabled = true
# Enable local logging
logflare_enabled = false

[analytics]
enabled = false

# Function hooks
[functions]
# Edge runtime version
edge_runtime = "v1"

# Experimental features
[experimental]
# Enable Postgres extensions management UI
extensions_ui = true
# Enable webhooks for real-time subscriptions
webhooks_enabled = true

# Database migrations and seeds
[db.seed]
# Enable automatic seeding after migrations
enabled = true
# SQL files to run as seeds
sql_paths = ["./seed.sql"]