import { useRef } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Printer, Download, Share2, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";

interface ClimateReportModalProps {
  open: boolean;
  onClose: () => void;
  location: string;
  climateData: any;
}

export default function ClimateReportModal({ 
  open, 
  onClose, 
  location, 
  climateData 
}: ClimateReportModalProps) {
  const reportRef = useRef<HTMLDivElement>(null);

  if (!climateData) return null;

  const handlePrint = () => {
    const printContent = reportRef.current?.innerHTML || '';
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Climate Report - ${location}</title>
          <style>
            body {
              font-family: system-ui, -apple-system, sans-serif;
              max-width: 800px;
              margin: 0 auto;
              padding: 20px;
              line-height: 1.6;
            }
            h1 { color: #004025; font-size: 24px; margin-bottom: 10px; }
            h2 { color: #004025; font-size: 18px; margin-top: 20px; }
            h3 { color: #333; font-size: 16px; margin-top: 15px; }
            .header { text-align: center; margin-bottom: 30px; }
            .date { color: #666; font-size: 14px; }
            .section { margin: 20px 0; padding: 15px; border: 1px solid #e0e0e0; border-radius: 8px; }
            .zone-badge { display: inline-block; padding: 4px 12px; background: #f0f9ff; color: #004025; border-radius: 4px; font-weight: 600; }
            .data-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 15px 0; }
            .data-item { padding: 10px; background: #f9f9f9; border-radius: 4px; }
            .label { font-weight: 600; color: #666; font-size: 14px; }
            .value { font-size: 16px; color: #333; margin-top: 4px; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; text-align: center; color: #666; font-size: 12px; }
            @media print {
              body { padding: 0; }
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          ${printContent}
          <div class="footer">
            <p>Generated by GardenScape Pro on ${new Date().toLocaleDateString()}</p>
            <p>Data source: Visual Crossing Weather API (${climateData.data_range?.total_years || 5}-year historical average)</p>
            <p>Analysis period: ${climateData.data_range?.date_range || 'Last 5 years'}</p>
          </div>
        </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const handleExport = () => {
    const reportData = {
      location,
      generated: new Date().toISOString(),
      climateData: {
        usda_zone: climateData.usda_zone,
        rhs_zone: climateData.rhs_zone,
        hardiness_category: climateData.hardiness_category,
        temperature_range: climateData.temperature_range,
        annual_rainfall: climateData.annual_rainfall,
        avg_temp_min: climateData.avg_temp_min,
        avg_temp_max: climateData.avg_temp_max,
        frost_dates: climateData.frost_dates,
        growing_season: climateData.growing_season,
        monthly_data: climateData.monthly_data
      }
    };

    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `climate-report-${location.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    const shareData = {
      title: `Climate Report - ${location}`,
      text: `Climate Report for ${location}\nUSDA Zone: ${climateData.usda_zone}\nRHS Zone: ${climateData.rhs_zone}\nAnnual Rainfall: ${climateData.annual_rainfall}mm\nGenerated by GardenScape Pro`,
      url: window.location.href
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (err) {
        console.log('Share cancelled or failed');
      }
    } else {
      // Fallback: Copy to clipboard
      const text = `${shareData.title}\n\n${shareData.text}\n\n${shareData.url}`;
      navigator.clipboard.writeText(text);
      alert('Report details copied to clipboard!');
    }
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader className="no-print">
          <DialogTitle>Climate Report</DialogTitle>
          <DialogDescription>
            Comprehensive climate analysis for {location}
          </DialogDescription>
          <div className="flex gap-2 pt-4">
            <Button onClick={handlePrint} size="sm" variant="outline">
              <Printer className="w-4 h-4 mr-2" />
              Print
            </Button>
            <Button onClick={handleExport} size="sm" variant="outline">
              <Download className="w-4 h-4 mr-2" />
              Export
            </Button>
            <Button onClick={handleShare} size="sm" variant="outline">
              <Share2 className="w-4 h-4 mr-2" />
              Share
            </Button>
          </div>
        </DialogHeader>

        <div ref={reportRef} className="space-y-6 pt-4">
          <div className="header">
            <h1>Climate Report</h1>
            <p className="text-lg font-medium">{location}</p>
            <p className="date">Generated on {new Date().toLocaleDateString()}</p>
            {climateData.data_range && (
              <p className="text-sm text-gray-600 mt-2">
                Based on {climateData.data_range.total_years} years of historical data 
                ({climateData.data_range.years_included?.join(', ')})
              </p>
            )}
          </div>

          <div className="section">
            <h2>Hardiness Zones</h2>
            <div className="data-grid">
              <div className="data-item">
                <div className="label">USDA Zone</div>
                <div className="value zone-badge">{climateData.usda_zone || 'N/A'}</div>
              </div>
              <div className="data-item">
                <div className="label">RHS Rating</div>
                <div className="value zone-badge">{climateData.rhs_zone || 'N/A'}</div>
              </div>
              <div className="data-item">
                <div className="label">Category</div>
                <div className="value">{climateData.hardiness_category || 'N/A'}</div>
              </div>
              <div className="data-item">
                <div className="label">Temperature Range</div>
                <div className="value">{climateData.temperature_range || 'N/A'}</div>
              </div>
            </div>
          </div>

          <div className="section">
            <h2>Climate Overview</h2>
            <div className="data-grid">
              <div className="data-item">
                <div className="label">Annual Rainfall (Historical Average)</div>
                <div className="value">{Math.round(climateData.annual_rainfall || 0)}mm</div>
              </div>
              <div className="data-item">
                <div className="label">Average Min Temperature (Historical)</div>
                <div className="value">{climateData.avg_temp_min?.toFixed(1)}°C</div>
              </div>
              <div className="data-item">
                <div className="label">Average Max Temperature (Historical)</div>
                <div className="value">{climateData.avg_temp_max?.toFixed(1)}°C</div>
              </div>
              <div className="data-item">
                <div className="label">Growing Season</div>
                <div className="value">{climateData.growing_season?.length || 0} days</div>
              </div>
            </div>
          </div>

          {climateData.frost_dates && (
            <div className="section">
              <h2>Frost Information</h2>
              <div className="data-grid">
                <div className="data-item">
                  <div className="label">Typical Last Frost</div>
                  <div className="value">
                    {climateData.frost_dates.last_frost 
                      ? new Date(climateData.frost_dates.last_frost).toLocaleDateString('en-US', { month: 'long', day: 'numeric' })
                      : 'No frost risk'}
                  </div>
                </div>
                <div className="data-item">
                  <div className="label">Typical First Frost</div>
                  <div className="value">
                    {climateData.frost_dates.first_frost
                      ? new Date(climateData.frost_dates.first_frost).toLocaleDateString('en-US', { month: 'long', day: 'numeric' })
                      : 'No frost risk'}
                  </div>
                </div>
              </div>
            </div>
          )}

          {climateData.monthly_data && (
            <div className="section">
              <h2>Monthly Averages</h2>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b">
                      <th className="text-left py-2">Month</th>
                      <th className="text-right py-2">Avg Temp (°C)</th>
                      <th className="text-right py-2">Rainfall (mm)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(climateData.monthly_data).map(([month, data]: [string, any]) => (
                      <tr key={month} className="border-b">
                        <td className="py-2">{month}</td>
                        <td className="text-right">{data.avg_temp?.toFixed(1)}</td>
                        <td className="text-right">{Math.round(data.total_rainfall || 0)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {climateData.gardening_advice && (
            <div className="section">
              <h2>Gardening Recommendations</h2>
              <p className="text-sm leading-relaxed">{climateData.gardening_advice}</p>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}