on:
  pull_request:
  
    branches: [ main ]
  workflow_dispatch:

jobs:
  db-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Sanity query
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          psql "$DATABASE_URL" -c "select now();"
