name: Supabase Connectivity/Auth Check

on: [workflow_dispatch]

jobs:
  check-connectivity:
    runs-on: ubuntu-latest
    steps:
      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Connectivity/auth check (pooled)
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          echo -n "$PGPASSWORD" | wc -c
          psql -v ON_ERROR_STOP=1 "postgresql://postgres:${PGPASSWORD}@db.uytzrsaagqzjhnmgbslq.supabase.co:6543/postgres?sslmode=require" \
            -c "select now(), current_user, inet_client_addr();"
